#!/bin/bash

[ "$1" = "install" -o "$1" = "upgrade" ] || exit 0

# Log start
INSTALL_LOG="@{product.log}/system/core/install.log"
echo "[$(date --rfc-3339=seconds)] @{package.name}-@{package.version}-@{package.release}.@{product.release}.@{system.distribution} preinstall start" >> "$INSTALL_LOG"

# Create user/group
getent group "@{package.group}" >/dev/null || groupadd -r "@{package.group}"
getent passwd "@{package.user}" >/dev/null || if [ "@{package.user}" = "@{product.user}" ]; then
	mkdir -p `dirname "@{package.root}"`
	useradd -g "@{package.group}" -d "@{package.root}" -c "@{product.name}" -s /bin/bash -m -r "@{package.user}"
else
	useradd -g "@{package.group}" -d "@{package.root}" -c "@{product.name} @{project.artifactId}" -s /sbin/nologin -M -r "@{package.user}"
fi

# Log end
echo "[$(date --rfc-3339=seconds)] @{package.name}-@{package.version}-@{package.release}.@{product.release}.@{system.distribution} preinstall success" >> "$INSTALL_LOG"
