#!/bin/bash

[ "$1" = "remove" ] || exit 0

# Log start/success
INSTALL_LOG="@{product.log}/system/core/install.log"
echo "[$(date --rfc-3339=seconds)] @{package.name} preremove start" >> "$INSTALL_LOG"
echo "[$(date --rfc-3339=seconds)] @{package.name} preremove success" >> "$INSTALL_LOG"
